shared:
  -
    name: Dusan
    testimonial: Switching jobs and overcoming the period between contracts was extremely painful. railsdevs.com is precisely what I needed. Now companies come to me instead of me chasing the work. I am incredibly grateful Joe did such a favor to the Rails community and built this platform.
    title: Freelancer
  -
    name: Felipe Vogel
    testimonial: During my search for my first dev job, out of all the many platforms and channels where I looked for work, railsdevs was the place where I had the most human and friendly interactions with potential employers. It was a breath of fresh air!
    title: Found First Dev Job
